### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by gree303** [mteillet/exrLayerMerger#1]
Hi,
this is exactly what I've been looking for. 
Also tried Imagemagick but it only supports single layer exr files.

I've tested your code but it results in the following error:
`C:\Denoiser\test

The following renderpasses have been detected:
1
2
3
Traceback (most recent call last):
  File "exrLayerMerge_v001.py", line 299, in <module>
    main()
  File "exrLayerMerge_v001.py", line 33, in main
    separatedList = listseparation(fileListUnderscores)
  File "exrLayerMerge_v001.py", line 110, in listseparation
    templist = [(fileListUnderscores[current][subCurrent][0][0]),(fileListUnderscores[current][subCurrent][0][1]),(fileListUnderscores[current][subCurrent][0][2]),(fileListUnderscores[current][subCurrent][1]),(fileListUnderscores[current][subCurrent][2])]
IndexError: list index out of range`

I'm using python 3.8.x on a Windows 10 x64 machine.
Within a test folder i've created 3 sub-folder with one *.exr file each.
test/1/1.exr
test/2/2.exr
test/3/3.exr

test/exrLayerMerge_v001.py

During process it creates a *.json file: exrMergingList.json -> C:\Denoiser\test

Also tried some python code for openexr but I wasn't able to find some useful help to combine single layer *.exr to multilayer *.exr.
 
Looking forward - Many thanks ahead.

**Comment by mteillet** [comment]
Hello,

Thanks for the feedback, could you email me the EXRs you are using ? I'll troubleshoot it as soon as I can.
Here's my email address: martin.teillet@hotmail.fr
If you can't could you please link the *.json file in question ? 

Thank you in advance :)

Martin Teillet

**Comment by gree303** [comment]
Thanks, sent you the link.
*the files I sent you are just images, not render layers. 
You could also just create 3 files in photoshop and export each as exr.

The json file is empty, no filenames listed. 
Just the path to the folder is included within the json file.

Could this be related to some missing exr header information?

Thank you.

**Comment by mteillet** [comment]
Perfect, I'll look into it as soon as I can

**Comment by mteillet** [comment]
Hello, I took some time to look into it.
This is due to how the tool is supposed to work. Its main focus is to work with CGI multilayered EXRs, as well as multiple render layers. If it does not detect other render layers, it will not output anyting.

Its hierarchy is designed to work with the output of a denoiser which splitted its output following this hierarchy.
C:/yourDirectory/aovDirectory/layername_AOV_filtered.frameNumber.exr

I will make a simplified version which will work for simpler hierarchy like the one you've sent me. It should be helpful for more people I guess.

Here's a splitted EXR I got after creating a "fake" renderlayer by copying & renaming your images as well as the folder structure.  
![image](https://user-images.githubusercontent.com/54497763/110654198-36e9e680-81be-11eb-8587-3dbbb5e9b191.png)

Martin

**Comment by gree303** [comment]
Thank you for the detailed description.
Looking forward to these changes.
